name = "GeometryOptimization"
uuid = "673bf261-a53d-43b9-876f-d3c1fc8329c2"
version = "0.1.4"
authors = ["JuliaMolSim community"]

[deps]
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[weakdeps]
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"

[extensions]
GeometryOptimizationOptimizationExt = "Optimization"

[compat]
AtomsBase = "0.5"
AtomsBuilder = "0.2.2"
AtomsCalculators = "0.2.3"
DocStringExtensions = "0.9"
LineSearches = "7"
Optim = "1.11.0"
Optimization = "3, 4, 5.5"
PrettyTables = "2"
StaticArrays = "1"
TestItemRunner = "0.2, 1"
TimerOutputs = "0.5.12"
Unitful = "1"
UnitfulAtomic = "1"
julia = "1.10"

[extras]
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
EmpiricalPotentials = "38527215-9240-4c91-a638-d4250620c9e2"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["AtomsBuilder", "EmpiricalPotentials", "Optimization", "OptimizationNLopt", "Test", "TestItemRunner"]
