name = "GeometryOptimization"
uuid = "673bf261-a53d-43b9-876f-d3c1fc8329c2"
authors = ["JuliaMolSim community"]
version = "0.0.1"

[deps]
ASEconvert = "3da9722f-58c2-4165-81be-b4d7253e8fd2"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
AtomsIO = "1692102d-eeb4-4df9-807b-c9517f998d44"
AtomsIOPython = "9e4c859b-2281-48ef-8059-f50fe53c37b0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[compat]
ASEconvert = "0.1"
AtomsBase = "0.3"
AtomsCalculators = "0.1"
DFTK = "0.6"
EmpiricalPotentials = "0.0.1"
Optimization = "3.20"
OptimizationOptimJL = "0.1"
StaticArrays = "1.8"
TestItemRunner = "0.2"
Unitful = "1.19"
UnitfulAtomic = "1.0"
julia = "1.9"

[extras]
ASEconvert = "3da9722f-58c2-4165-81be-b4d7253e8fd2"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
EmpiricalPotentials = "38527215-9240-4c91-a638-d4250620c9e2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
examples = ["DFTK", "ASEconvert", "EmpiricalPotentials"]
test = ["Test", "TestItemRunner"]
