[deps]
ASEconvert = "3da9722f-58c2-4165-81be-b4d7253e8fd2"
AtomsBase = "a963bdd2-2df7-4f54-a1ee-49d51e6be12a"
AtomsBuilder = "f5cc8831-eeb7-4288-8d9f-d6c1ddb77004"
AtomsCalculators = "a3e0e189-c65a-42c1-833c-339540406eb1"
AtomsIO = "1692102d-eeb4-4df9-807b-c9517f998d44"
DFTK = "acf6eb54-70d9-11e9-0013-234b7a5f5337"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EmpiricalPotentials = "38527215-9240-4c91-a638-d4250620c9e2"
GeometryOptimization = "673bf261-a53d-43b9-876f-d3c1fc8329c2"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationNLopt = "4e6fcdb7-1186-4e1f-a706-475e75c168bb"
PseudoPotentialData = "5751a51d-ac76-4487-a056-413ecf6fbe19"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAtomic = "a7773ee8-282e-5fa2-be4e-bd808c38a91a"

[sources]
GeometryOptimization = {path = ".."}

[compat]
ASEconvert = "0.1.8"
AtomsBase = "0.5.2"
DFTK = "0.7"
Documenter = "~1.8"
EmpiricalPotentials = "0.2.5"
OptimizationNLopt = "0.3.9"
PseudoPotentialData = "0.2"
Unitful = "1.28.0"
